name: (all packages) Static Analysis
on:
  push:
    branches: [main]
  schedule:
    - cron: '23 19 * * 4'
jobs:
  codeQL:
    name: CodeQL Checks
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
